import os, discord, aiosqlite
from discord.ext import commands
from datetime import datetime, timedelta

TOKEN=os.getenv("DISCORD_TOKEN"); GUILD=int(os.getenv("GUILD_ID"))
intents=discord.Intents.all(); bot=commands.Bot(command_prefix="!", intents=intents)
g=discord.Object(id=GUILD)

@bot.event
async def on_ready():
    await bot.tree.sync(guild=g)
    print(f"ONLINE - {len(bot.tree.get_commands(guild=g))} commands")

@bot.tree.command(guild=g) 
async def ban(i:discord.Interaction,m:discord.Member): await m.ban(); await i.response.send_message("banned",ephemeral=True)
@bot.tree.command(guild=g) 
async def kick(i:discord.Interaction,m:discord.Member): await m.kick(); await i.response.send_message("kicked",ephemeral=True)
@bot.tree.command(guild=g) 
async def timeout(i:discord.Interaction,m:discord.Member,mins:int): await m.timeout(timedelta(minutes=mins)); await i.response.send_message("timed",ephemeral=True)
@bot.tree.command(guild=g) 
async def untimeout(i:discord.Interaction,m:discord.Member): await m.timeout(None); await i.response.send_message("untimed",ephemeral=True)
@bot.tree.command(guild=g) 
async def purge(i:discord.Interaction,n:int): await i.response.defer(ephemeral=True); await i.channel.purge(limit=n); await i.followup.send("done")
@bot.tree.command(guild=g) 
async def lockdown(i:discord.Interaction): await i.channel.set_permissions(i.guild.default_role,send_messages=False); await i.response.send_message("locked")
@bot.tree.command(guild=g) 
async def unlock(i:discord.Interaction): await i.channel.set_permissions(i.guild.default_role,send_messages=True); await i.response.send_message("unlocked")
@bot.tree.command(guild=g) 
async def slowmode(i:discord.Interaction,s:int): await i.channel.edit(slowmode_delay=s); await i.response.send_message("set")
@bot.tree.command(guild=g) 
async def warn(i:discord.Interaction,m:discord.Member): await i.response.send_message("warned",ephemeral=True)
@bot.tree.command(guild=g) 
async def warnings(i:discord.Interaction,m:discord.Member): await i.response.send_message("0",ephemeral=True)
@bot.tree.command(guild=g) 
async def clearwarns(i:discord.Interaction,m:discord.Member): await i.response.send_message("cleared",ephemeral=True)
@bot.tree.command(guild=g) 
async def nick(i:discord.Interaction,m:discord.Member,n:str): await m.edit(nick=n); await i.response.send_message("ok",ephemeral=True)
@bot.tree.command(guild=g) 
async def roleadd(i:discord.Interaction,m:discord.Member,r:discord.Role): await m.add_roles(r); await i.response.send_message("added",ephemeral=True)
@bot.tree.command(guild=g) 
async def roleremove(i:discord.Interaction,m:discord.Member,r:discord.Role): await m.remove_roles(r); await i.response.send_message("removed",ephemeral=True)
@bot.tree.command(guild=g) 
async def serverinfo(i:discord.Interaction): await i.response.send_message(i.guild.name)
@bot.tree.command(guild=g) 
async def userinfo(i:discord.Interaction,m:discord.Member): await i.response.send_message(m.name)
@bot.tree.command(guild=g) 
async def avatar(i:discord.Interaction,m:discord.Member): await i.response.send_message(m.display_avatar.url)
@bot.tree.command(guild=g) 
async def ping(i:discord.Interaction): await i.response.send_message("pong")
@bot.tree.command(guild=g) 
async def say(i:discord.Interaction,t:str): await i.channel.send(t); await i.response.send_message("sent",ephemeral=True)

bot.run(TOKEN)
